# Generated by Django 4.2.18 on 2025-01-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uservpn',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
