# Generated by Django 4.2.18 on 2025-05-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rootVPN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('load_coef', models.FloatField(default=0.0)),
                ('max_speed_in_mbps', models.FloatField(default=200.0)),
                ('active_users', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVPN',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(db_index=True, max_length=100, null=True, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('last_payment', models.DateTimeField(null=True)),
                ('days_at_subscribe', models.IntegerField(null=True)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='rootVPN.server')),
            ],
        ),
    ]
