# Generated by Django 4.2.18 on 2025-01-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0002_alter_server_id_alter_uservpn_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservpn',
            old_name='id',
            new_name='user_id',
        ),
    ]
