# Generated by Django 4.2.18 on 2025-05-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservpn',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
