# Generated by Django 4.2.18 on 2025-05-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0003_alter_uservpn_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservpn',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
