# Generated by Django 4.2.18 on 2025-05-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0004_alter_uservpn_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservpn',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
