# Generated by Django 4.2.18 on 2025-01-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0004_rename_user_id_uservpn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservpn',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
