# Generated by Django 4.2.18 on 2025-01-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0005_uservpn_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='load_coef',
            field=models.FloatField(default=0.0),
        ),
    ]
