# Generated by Django 4.2.18 on 2025-05-02 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0005_alter_uservpn_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservpn',
            name='days_at_subscribe',
        ),
        migrations.RemoveField(
            model_name='uservpn',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='uservpn',
            name='last_payment',
        ),
        migrations.RemoveField(
            model_name='uservpn',
            name='password',
        ),
        migrations.RemoveField(
            model_name='uservpn',
            name='server',
        ),
        migrations.RemoveField(
            model_name='uservpn',
            name='username',
        ),
        migrations.AddField(
            model_name='uservpn',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='uservpn',
            name='is_blocked',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100, null=True)),
                ('last_payment', models.DateTimeField(null=True)),
                ('days_at_subscribe', models.IntegerField(null=True)),
                ('username', models.CharField(db_index=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to='rootVPN.server')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to='rootVPN.uservpn')),
            ],
        ),
    ]
