# Generated by Django 4.2.18 on 2025-05-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0006_remove_uservpn_days_at_subscribe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='api_password',
            field=models.CharField(default='securepassword', max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='api_username',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
