# Generated by Django 4.2.18 on 2025-01-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0007_server_max_speed_in_mbps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descryption', models.CharField(max_length=300)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='active_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uservpn',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descryption', models.CharField(max_length=300)),
                ('cost_in_day', models.FloatField(default=0.0)),
                ('max_number_of_devices', models.IntegerField(default=1)),
                ('max_speed_in_mbps', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff', to='rootVPN.uservpn')),
            ],
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('balance', models.FloatField(default=50.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='rootVPN.uservpn')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='rootVPN.uservpn')),
            ],
        ),
    ]
