# Generated by Django 4.2.18 on 2025-01-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0007_server_max_speed_in_mbps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='max_speed_in_mbps',
            field=models.FloatField(default=200.0),
        ),
    ]
