# Generated by Django 4.2.18 on 2025-01-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0008_promocode_server_active_users_alter_uservpn_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservpn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
