# Generated by Django 4.2.18 on 2025-01-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0008_alter_server_max_speed_in_mbps'),
        ('rootVPN', '0009_alter_uservpn_id'),
    ]

    operations = [
    ]
