# Generated by Django 4.2.18 on 2025-01-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0010_merge_20250127_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='user',
        ),
        migrations.AddField(
            model_name='uservpn',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff', to='rootVPN.tariff'),
        ),
    ]
