# Generated by Django 4.2.18 on 2025-01-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0011_remove_tariff_user_uservpn_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='active_users',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
