# Generated by Django 4.2.18 on 2025-01-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0012_alter_server_active_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
