# Generated by Django 4.2.18 on 2025-01-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootVPN', '0013_alter_server_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariff',
            old_name='cost_in_day',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='tariff',
            name='days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='uservpn',
            name='last_payment',
            field=models.DateTimeField(null=True),
        ),
    ]
